# /etc/dovecot/dovecot.conf

# ----------------------------------------------------
# Protocoles utilisés : IMAP (lecture), LMTP (livraison)
# ----------------------------------------------------
protocols = imap lmtp
listen = *

# ----------------------------------------------------
# Authentification
# ----------------------------------------------------
disable_plaintext_auth = no         # Pas de chiffrement, OK en labo
auth_mechanisms = plain
first_valid_uid = 100               # vmail = uid 101, donc requis

# ----------------------------------------------------
# Auth par fichier texte
# Format : user:{PLAIN}motdepasse
# ----------------------------------------------------
passdb {
  driver = passwd-file
  args   = /etc/dovecot/passwd
}

# ----------------------------------------------------
# Tous les utilisateurs virtuels ont le même UID/GID
# %n = nom sans @
# home = /var/mail/vmail/<user>
# ----------------------------------------------------
userdb {
  driver = static
  args   = uid=101 gid=104 home=/var/mail/vmail/%n
}

# ----------------------------------------------------
# Format de stockage des mails : Maildir (1 fichier par mail)
# ~/ = répertoire home défini plus haut
# ----------------------------------------------------
mail_location = maildir:~/Maildir

# ----------------------------------------------------
# LMTP : réception des mails depuis Postfix
# ----------------------------------------------------
service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode  = 0600
    user  = postfix
    group = postfix
  }
}

# ----------------------------------------------------
# Socket d’auth utilisé par Postfix
# ----------------------------------------------------
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode  = 0660
    user  = postfix
    group = postfix
  }
}

# ----------------------------------------------------
# Logs (redirigés éventuellement vers stdout/stderr dans Docker)
# ----------------------------------------------------
log_path       = /var/log/dovecot.log
auth_verbose   = yes
auth_debug     = yes
