[supervisord]
nodaemon=true

[program:postfix]
command=/usr/sbin/postfix start-fg
priority=10
autorestart=true

[program:dovecot]
command=/usr/sbin/dovecot -F
priority=20
autorestart=true

[program:mail-log]
command=tail -F /var/log/mail.log
autorestart=true
